site_name: pot
nav:
    - Home: index.md
    - HowTos:
        - Getting started: Getting.md
        - Full installation guide: Installation.md
        - "Thin Jails": Thin.md
        - "Thick Jails": Thick.md
        - Containers: Container.md
        - Volumes: Volumes.md
        - Snapshot: Snapshot.md
        - Network configuration: Network.md
        - Images: Images.md
    - Old HowTos:
        - QuickStart: QuickStart.md
    - F.A.Q.: FAQ.md

site_name: 'pot'
site_url: 'https://pot.pizzamig.dev/'
site_description: 'Another jail framework aiming to improve container-based workflows'
site_author: 'Luca Pizzamiglio'
repo_name: 'pizzamig/pot/'
repo_url: 'https://github.com/pizzamig/pot/'
edit_uri: ''
theme:
  name: 'material'
  feature:
  palette:
    primary: 'teal'
    accent: 'red'
  icon:
    logo: po-red.svg
  font: false
  favicon: pot-red.svg
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: 'https://github.com/pizzamig'
    - icon: fontawesome/brands/twitter
      link: 'https://twitter.com/pizzamig'
    - icon: fontawesome/brands/linkedin
      link: 'https://www.linkedin.com/in/pizzamiglio'
markdown_extensions:
    - admonition
    - toc:
        permalink: true
    - pymdownx.superfences
    - pymdownx.details
    - pymdownx.keys
plugins:
  - search
  - minify:
      minify_html: true
  - git-revision-date-localized:
      type: timeago
